### ISSUE TITLE
ST_H3_POLYFILLFROMGEOG problem

### ISSUE THREAD

**Issue by bilus** [CartoDB/bigquery-jslibs#12]
First of all, an amazing idea to package these functions as a public dataset.

I'm having a problem using `ST_H3_POLYFILLFROMGEOG`. My original problem was trying to polyfill Germany but I think it's also apparent here.

Compare what you show in the [article](https://carto.com/blog/spatial-functions-bigquery-uber/)

![image](https://user-images.githubusercontent.com/1025537/82695945-5717db80-9c66-11ea-940f-913e2e2b86bf.png)

to what I get in Bigquery Geo Viz using the same SQL:

![image](https://user-images.githubusercontent.com/1025537/82696068-99d9b380-9c66-11ea-8c1f-26c3fd2a8b66.png)

The same (?) thing happens for me in Germany, these are hexagons I'm getting:

```
WITH countries AS (SELECT country, jslibs.h3.ST_H3_POLYFILLFROMGEOG(geometry,8) AS cells, geometry
       FROM `conrad-analytics-staging.public.administrative_boundaries`)
SELECT 'red' as stroke, geometry, jslibs.h3.ST_H3_BOUNDARY(cell) AS geom FROM countries, UNNEST(countries.cells) AS cell
WHERE country = 'Germany'
```

![image](https://user-images.githubusercontent.com/1025537/82696686-cb9f4a00-9c67-11ea-98f4-9da9e5679bce.png)

This the boundary it polyfills:

![image](https://user-images.githubusercontent.com/1025537/82696768-f9848e80-9c67-11ea-8fd8-cc479753d199.png)

**Comment by bilus** [comment]
I have a working fix.

**Comment by jatorre** [comment]
Thanks, looking forward to it in fact!

**Comment by jatorre** [comment]
Hey @bilus ewill you be able to share that PR=

**Comment by bilus** [comment]
I will over the weekend. Sorry got distracted by work. :P

**Comment by cmulligann-glx** [comment]
Thanks for looking at this guys. I'm uniquely unqualified to fix any JS, but here's a quick workaround for everyone who can't wait for @bilus to take some holiday ;)

`WITH polys AS (
  SELECT *
  FROM UNNEST((SELECT ST_DUMP(geog) FROM `project_id.schema_id.table_with_single_row`)) AS geog
), polyh3 AS (
  SELECT jslibs.h3.polyfillFromGeoJson(ST_ASGEOJSON(geog), 7) AS h3arr
  FROM polys
)
SELECT h3res07
FROM polyh3 CROSS JOIN UNNEST(polyh3.h3arr) AS h3res07`

Essentially, I first dump the MultiPolygon and then polyfill the (simple) polygons separately.

**Comment by bilus** [comment]
Sorry, wasn't unable to submit the PR on Sunday as planned because there was an outage I got dragged into but here's my code:

```sql
CREATE OR REPLACE FUNCTION `....`.polyfillFromGeoJson(geojson STRING, resolution NUMERIC)
 RETURNS ARRAY<STRING>
 LANGUAGE js AS
"""

  const featureGeometry = JSON.parse(geojson)

  if (!['Polygon', 'MultiPolygon'].includes(featureGeometry.type)) {
    throw new Error(`Unsupported geometry type ${featureGeometry.type}`);
  }

  const polygonCoordinates =
    featureGeometry.type === 'MultiPolygon'
      ? featureGeometry.coordinates
      : [featureGeometry.coordinates];

  const hexes = polygonCoordinates.reduce(
    (acc, coordinates) => acc.concat(h3.polyfill(coordinates, resolution, true)),
    []
  );

  return hexes;
"""
OPTIONS (
  library=["gs://bigquery-jslibs/h3-js.umd.js"]
);

CREATE OR REPLACE FUNCTION `...`.ST_H3_POLYFILLFROMGEOG(geo GEOGRAPHY, resolution NUMERIC) AS (
	polyfillFromGeoJson(ST_ASGEOJSON(geo),resolution)
);
```

**Comment by jatorre** [comment]
Thanks, I hve submitted the changes now and deployed the functions.

If you want to submit a PR with those cases that will be great.
Thanks for the code.
