### ISSUE TITLE
System Error Using ST_H3_POLYFILLFROMGEOG()

### ISSUE THREAD

**Issue by mmartimo** [CartoDB/bigquery-jslibs#21]
The following example code (and all my internal queries) are all resulting with the error:
`SyntaxError: Unexpected token if at UDF$2(STRING, NUMERIC) line 1, columns 45-47`

```
WITH data as (
	SELECT jslibs.h3.compact(
  	jslibs.h3.ST_H3_POLYFILLFROMGEOG(tract_geom,11)) as geo 
  	FROM `bigquery-public-data.geo_census_tracts`.census_tracts_new_york 
  	WHERE geo_id='36081000100')

SELECT jslibs.h3.ST_H3_BOUNDARY(h3) as h3geo 
FROM data,UNNEST(geo) as h3
```

**Comment by matiasduran** [comment]
Hi, since a couple of days I get the same error every time I run ST_H3_POLYFILLFROMGEOG. A week ago it worked fine (exactly the same code).

Thank you in advance!

**Comment by jatorre** [comment]
Aghh, we definetly need to add a level of unit testing on this... I have repdeployed now and not it is working, but I dont know why the deployment scripts break certain functions from time to time.

We will get into it very soon, meanwhile, please keep pinging us for failing functions.
