### ISSUE TITLE
jslibs not available in regions other than US

### ISSUE THREAD

**Issue by bencohen111** [CartoDB/bigquery-jslibs#3]
Hi Javier,

I just came across [your article](https://carto.com/blog/spatial-functions-bigquery-uber/) and I really like it! I was particularly impressed by the fact that it instantly runs in BigQuery.

But I walked into one issue, when I'm running the functions on our internal datasets, it doesn't work. And I get the error: "function not found"
![image](https://user-images.githubusercontent.com/18191234/70458536-87056500-1ab2-11ea-90a3-f97350015879.png)

Not 100% sure, but I think this is because the function is only available in the US-region (if I run it on a US dataset it does work). 

Are you planning to deploy these functions in other regions apart from the US, or should we just figure this out by ourselves? 

Thanks either way for building this great addition to BQ!

**Comment by baristahell** [comment]
I'm trying to use them too and ended up installing the functions on my Cloud Shell. That being said, I've got a permission error despite being Admin. Did you encounter this issue?
Thanks

**Comment by jtmiclat** [comment]
@baristahell The `project_id` you pass should be the project you are running the query on and not the `jslibs`.  If you plan to upload as a different project, you would need to change the project it is being saved on within `jslibs/sql/proj4js/proj4.sql`. This means changing `jslibs.proj4js.proj4` to `<your_project>.<your_dataset>.proj4`.  Hope this helps!

**Comment by francois-baptiste** [comment]
@baristahell 
Yes @jtmiclat is right, the whole project is hardlinked to the bucket `jslibs`. If you plan to upload as a different project, you better fork the project and replace  `jslibs` with your bucket name in your region of preference

**Comment by francois-baptiste** [comment]
Even GCP seems to have the same problem...
[https://github.com/GoogleCloudPlatform/bigquery-utils/issues/2](url)

**Comment by jatorre** [comment]
The idea of the project was to host the functions so that users did not  have to install them on their repos. I assume we will need to create the jslibs projects on every region to have them available. @fhoffa  Can you help us in here? Whats the recommended approach?

**Comment by fhoffa** [comment]
Indeed - to have the datasets usable from other regions, the dataset needs to be copied to a dataset in that region.

For example, a new dataset could be called `jslibs.h3_eu` or `jslibs.eu_h3`.

There's an easy way to copy between regions:

- https://console.cloud.google.com/marketplace/details/bigquery-data-connectors/cross_region_copy

But probably just re-running the build script with the different dataset name should suffice.

**Comment by baristahell** [comment]
Oh yeah I'm sorry I haven't got any notification for your answers, it was just a misunderstanding on my end and we fixed it with a coworker who's a bit smarter than myself  ^^'
Thanks thought !

**Comment by francois-baptiste** [comment]
I have created a jslibs replicate region called libjs4eu for EU and libjs4us for US.

For instance:
```
SELECT libjs4eu.h3.ST_H3(position_geom, 8)
FROM `bigquery-public-data.catalonian_mobile_coverage_eu.mobile_data_2015_2017`
WHERE date = "2016-02-28" LIMIT 1000
```

```
SELECT libjs4us.h3.ST_H3(position_geom, 8)
FROM `bigquery-public-data.catalonian_mobile_coverage.mobile_data_2015_2017`
WHERE date = "2016-02-28" LIMIT 1000
```

**Comment by jatorre** [comment]
This is great! We should advertise this... but we need to come up with a convention and decission on how to host them. Thanks for doing this meanwhile.

What do you think on using something like **jslibs_eu** and **jslibs_us**?

I am also happy with yours but I will need a service account to deploy there.

Thanks again!

**Comment by francois-baptiste** [comment]
Thanks @jatorre 

Yes **jslibs_eu** and  **jslibs_us** are also great project name except that you should escape underscore on SQL queries... We could also keep the project name an make several dataset for each region as @fhoffa says...

I prefer to keep libjs4eu and libjs4us as (my) unstable branch / bleeding edge (integrating @SMazu pull request for instance)

You could also propose a merge request to https://github.com/GoogleCloudPlatform/bigquery-utils/tree/master/udfs/community , they are on CI/CD from their github project but they lack the multi region support.

**Comment by jatorre** [comment]
Allright, went ahead an implemented @fhoffa suggestion. Now the functions are created in 3 forms when deployed:

```
jslibs.h3.ST_H3
jslibs.us_h3.ST_H3
jslibs.eu_h3.ST_H3
```
I have kept the non qualified version for backward compatibility. The deploy_functions script now takes care of the entire deployment, which is great and the only way now with this complexity.

**Comment by muscovitebob** [comment]
Hi @fhoffa a bit off topic but is your own dataset `fhoffa.x` available anywhere in the EU or maybe its source so I can replicate some of the functions to my own datasets?

**Comment by rochakarora77** [comment]
The provided library in the europe and us region works fine with the shared datasets but, if someone wants to use it with their internal dataset it gives an error. This is the same case as described by Ben at the beginning of this thread. I want to use the eu_h3.ST_H3 library function against the data I have in my table residing in a dataset in europe-west2 region. The query gives an error on my internal dataset table in the from clause "datasetA.tableA" not found in region EU. 
Am I missing something ?
