### ISSUE TITLE
Function not found: `jslibs.eu_s2.ST_S2`

### ISSUE THREAD

**Issue by francois-baptiste** [CartoDB/bigquery-jslibs#9]
@jatorre Thank you for the replication of datasets in the EU.
It seems however that `jslibs.eu_s2.ST_S2` is missing...

**Comment by jatorre** [comment]
Thats weird, rerun them and I can see it now there... can you confirm?

**Comment by francois-baptiste** [comment]
Yes it's working now! Thanks.
